Updated NvTransform to do scale, crop and color transform
Apra-Labs/ApraPipes pull request #176
Opened 2022-11-04 11:59 UTC by yashrajsapra

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #175 
**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2022-11-08 07:17 UTC, kumaakh requested changes
need tests which run during build.

2022-11-08 07:17 UTC, kumaakh commented on base/test/nvtransform_tests.cpp
> +BOOST_AUTO_TEST_CASE(crop, *boost::unit_test::disabled())
Please add similar tests with FileReader, if these tests remain "disabled" we will ahve regressions.

2022-11-10 12:37 UTC, kumaakh requested changes
need tests which show if feature works... there are other smaller comments as well

2022-11-10 12:54 UTC, yashrajsapra commented
Yeah Akhil, I will work on that


On Thu, Nov 10, 2022 at 6:07 PM Akhil Kumar ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> need tests which show if feature works... there are other smaller comments
> as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Apra-Labs/ApraPipes/pull/176#pullrequestreview-1175693164>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAQDXMWXJYJ4MZ5GOTS6ZLWHTUCDANCNFSM6AAAAAARXDN7U4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-07 07:33 UTC, yashrajsapra commented
> need tests which show if feature works... there are other smaller comments as well

Hi Akhil,
Need to push a new module for doing a memory conversion from host to dma

2023-07-17 10:57 UTC, mraduldubey approved these changes

2023-07-19 11:44 UTC, merged