Mp4ReaderSource module - version 2
Apra-Labs/ApraPipes pull request #268
Opened 2023-07-19 10:53 UTC by mohammedzakikochargi

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

**Description**
The new version of Mp4Reader has the following upgrades - 
Ordered cache of files integration - jpeg and h264
Seek refactoring - jpeg and h264
Reverse play - jpeg

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**

Type Choose one: (Bug fix | Feature | Documentation | Testing | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2023-07-24 13:57 UTC, mraduldubey requested changes

2023-07-24 13:57 UTC, mraduldubey commented on base/src/OrderedCacheOfFiles.cpp
> +	for(auto& mp4File : mp4Files)
videoFIle = mp4File.begin()->string();

2023-07-24 13:57 UTC, mraduldubey commented on base/src/OrderedCacheOfFiles.cpp
> +	if (mp4Files.size())
instead:
check size, if empty, return false
else, sort and assign first video file

2023-07-24 13:57 UTC, mraduldubey commented on base/src/OrderedCacheOfFiles.cpp
> +	LOG_ERROR << "video cache size = " << videoCache.size();
make it log_info

2023-07-27 11:32 UTC, mraduldubey requested changes
Recheck all the files & address comments

2023-07-27 12:09 UTC, mohammedzakikochargi commented on base/include/Command.h
yes, as we discussed we'll create a separate PR for it

2023-07-28 06:14 UTC, mohammedzakikochargi commented on base/include/OrderedCacheOfFiles.h
done

2023-07-28 06:27 UTC, mraduldubey approved these changes

2023-07-28 12:27 UTC, merged