EnhancedDMAFDWrapper
Apra-Labs/ApraPipes pull request #279
Opened 2023-08-03 13:06 UTC by venkat0907

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #278 

**Description**

currently with memcpy we were just able to read the buffer we are unable to write , so i change it to Read_write 

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

we had three enum's  read , write , read_write wen can have support of three and make it user choice , but we have to change so many modules internally can implement this in future

Type Choose one: (Bug fix | Feature | Documentation | Testing | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2023-08-04 07:52 UTC, yashrajsapra approved these changes

2023-08-08 13:20 UTC, mraduldubey requested changes

2023-08-08 14:17 UTC, venkat0907 commented on base/test/frame_factory_test_dma.cpp
> +    }
added check after memset and checked whether every byte has 200

2023-08-10 11:08 UTC, mraduldubey approved these changes

2023-08-10 13:11 UTC, merged