GenericMemConversionModule
Apra-Labs/ApraPipes pull request #283
Opened 2023-08-07 11:19 UTC by venkat0907

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #248 

**Description**
written a generic Memory conversion module that can convert :-
-> Dma to Host
-> Host to Dma[currently not supporting planar images]
-> Device to DMA
-> DMA to Device
-> Host to Device
-> Device to Host

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

NO

Type Choose one: Feature

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2023-08-21 07:12 UTC, yashrajsapra requested changes

2023-08-21 07:12 UTC, yashrajsapra commented on base/include/MemTypeConversion.h
> +#include <memory>
Move "<memory >" header from include to src file

2023-08-21 07:12 UTC, yashrajsapra commented on base/include/DMAFrameUtils.h
>              auto rawMetadata = FrameMetadataFactory::downcast<RawImageMetadata>(metadata);
Please format all the files

2023-08-21 07:13 UTC, venkat0907 commented on base/include/DMAFrameUtils.h
>              auto rawMetadata = FrameMetadataFactory::downcast<RawImageMetadata>(metadata);
sure

2023-08-21 07:14 UTC, venkat0907 commented on base/test/memtypeconversion_tests.cpp
sure done

2023-08-21 12:59 UTC, venkat0907 commented on base/test/memtypeconversion_tests.cpp
> +	memconversion3->setNext(sink);
added save or compare for assertion

2023-08-23 07:36 UTC, yashrajsapra approved these changes

2023-08-23 09:21 UTC, mraduldubey approved these changes

2023-08-23 11:11 UTC, merged