Mp4Reader getSetProps enhancement
Apra-Labs/ApraPipes pull request #294
Opened 2023-08-18 11:09 UTC by mohammedzakikochargi

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #273 

**Description**
Did Mp4Reader changes related to following cases and added test for them:

Changing file path from custom file name to only root dir and vice versa.
Changing filename to only root dir and vice versa.

Precise description of the changes in this pull request

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**

Type Choose one: (Bug fix | Feature | Documentation | Testing | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2023-08-18 13:58 UTC, mraduldubey requested changes

2023-08-18 13:58 UTC, mraduldubey commented on base/include/Mp4ReaderSource.h
> +		if (parseFS && boost::filesystem::path(videoPath).extension() == ".mp4")
put a comment on the logic for skipDir

2023-08-21 10:44 UTC, mohammedzakikochargi commented on base/include/Mp4ReaderSource.h
> +		if (parseFS && boost::filesystem::path(videoPath).extension() == ".mp4")
Added comments explaining the logic

2023-08-22 20:06 UTC, mraduldubey approved these changes

2023-08-23 04:18 UTC, merged