Added the get, set props instead of hardcoded values and directly converting the aprapoint3f to vtkDataArray
Apra-Labs/ApraPipes pull request #350
Opened 2024-05-02 10:02 UTC by K-aniket23

Title: Enhance vtkIntegartion Module: Data Handling and Property Management

Description:
This pull request enhances the VTK module by improving data handling efficiency and flexibility:    

1: Employed VTK functions to copy data from aprapoints3f to a vtkArray, eliminating the need to copy data from aprapoints3f to vtkPoints using a for loop.

2: Added getProps and setProps functions to replace hardcoded values for properties, enhancing flexibility.

3: Implemented unit tests to evaluate the functionality of the newly added get and setProps functions.

2024-05-08 10:57 UTC, abhi9sh requested changes

2024-05-08 10:57 UTC, abhi9sh commented on base/src/STLRendererSink.cpp
> +	STLRendererSinkProps props;
declare this props at top

2024-05-08 10:59 UTC, abhi9sh requested changes

2024-05-08 10:59 UTC, abhi9sh commented on base/test/stlrenderer_tests.cpp
use sensible variable name

2024-05-08 14:31 UTC, K-aniket23 commented on base/include/STLRendererSink.h
> +		bkgColor = _bkgColor;
should i do this as it would not be more clean and clear code

2024-05-13 12:27 UTC, mraduldubey approved these changes

2024-05-13 12:30 UTC, mraduldubey requested changes

2024-05-13 12:30 UTC, mraduldubey commented on base/test/stlrenderer_tests.cpp
> +	{
yes

2024-05-13 12:30 UTC, mraduldubey commented on base/test/stlrenderer_tests.cpp
> +	{
Ideally, should be read from file. Best way is to use vtk itself to read and iterate over the vtkarray to give  the points when source module does step ()

2024-07-04 12:15 UTC, merged