Affine transform
Apra-Labs/ApraPipes pull request #51
Opened 2022-01-13 12:53 UTC by yashrajsapra

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

 #36 

**Description**

Added Affine Transform Module. 
Currently supported only for jetson boards.

**Alternative(s) considered**

**Type**

Feature

**Screenshots (if applicable)**

**Checklist**

- [ ] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2022-01-13 14:18 UTC, kumaakh commented
Why not add a couple of test cases pls ? @yashrajsapra @joiskash

2022-01-17 07:31 UTC, joiskash requested changes
Thanks @yashrajsapra for this PR! I have done an initial round of review. Please address the comments. Also as Akhil has requested , please add some unit tests. Make sure you go through the checklist before adding them.

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +		if (mFrameType == FrameMetadata::RAW_IMAGE)
Why is this if statement required? I think the switch case above is already taking care of this

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +			int x, y, w, h;
What is x and y? use width and height instead of w an h. Use more explanatory variable names instead of x & y

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +			RawImageMetadata outputMetadata(w, h, rawMetadata->getImageType(), rawMetadata->getType(), 512, rawMetadata->getDepth(), FrameMetadata::DMABUF, true);
What is the hard coded value of 512?

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	NppStreamContext nppStreamCtx;
Move this above the function for better readability

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	NppiSize srcSize[4];
Add comments for the variables that are tough to understand explaining in one line what they are for.

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +			shx = (1 - co) * (srcSize[0].width / 2) + si * srcSize[0].height / 2;
Try not to use acronyms that are not standard. Not sure what shx means

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	auto frame = frames.cbegin()->second;
Put a isFrameEmpty check

2022-01-17 07:31 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	cudaFree(0);
Do we always have to call cudaFree?

2022-01-17 08:03 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	cudaFree(0);
You can put this in processSOS

2022-01-17 08:11 UTC, joiskash commented on base/src/AffineTransform.cpp
> +	cudaMemset(static_cast<DMAFDWrapper *>(outFrame->data())->getCudaPtr(), 0, outFrame->size());
Change this to cudaMemsetAsync and pass the Cuda stream. Avoid using the default cuda stream. In Compute you are using stream so here also you can use the same

2022-02-02 08:10 UTC, joiskash commented
@yashrajsapra please update this branch and lets try to close it by this week. We only need to support DMA and GPU . Later enhancement can be to check pin input type and then based on that use DMA/GPU or CPU memory

2022-02-15 07:00 UTC, joiskash commented
@yashrajsapra any updates?

2023-07-28 13:05 UTC, closed without merging

2023-07-28 13:06 UTC, mraduldubey commented
This has a been addressed in #227 now